### PR TITLE
fix: UI layouts for topbar and sidebar

### PR DESCRIPTION
**Pull request by ayoubbajjou**
All the changes should be in this PR.

### CODE REVIEW

**Comment by mabumusa1** [comment]
@ayoubbajjou 
The PR looks good, few comments on the UI:

- There is a difference in the style of the logo on mobile and web, can we unify that? either by making the aside to be light which can be found under `config/skin/global.php` or by changing the style of the logo to be light on a dark aside (I prefer this).

- The menu overlay the content, we need this fixed 
image

- There are missing elements like `Create Team` and `Team Settings` which need to be added.

**Comment by ayoubbajjou** [comment]
Ok I'll take care of those changes and push again.

**Comment by ayoubbajjou** [comment]
btw we don't have light logo ?

**Review by mabumusa1 — APPROVED** [review]
Changes added as requested, thanks @ayoubbajjou

**Pull request merged**
